name: Example pipeline with test report demo

on:
  push:
    branches: [ '*' ]
  workflow_dispatch: {}

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      checks: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Prepare junit report
      id: cargo_reporter 
      uses:  innoq/action-cargo-test-report@main
      with:
        cargo-test-report-json: '.github/workflows/results-with-all-states.json'

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@main
      if: always() # always run even if the previous step fails
      with:
        check_name: Test Report
        fail_on_failure: true
        require_tests: true
        summary: ${{ steps.cargo_reporter.outputs.summary }}
